// <auto-generated />
using System;
using EcoPoints.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EcoPoints.Api.Migrations
{
    [DbContext(typeof(EcoPointsDbContext))]
    [Migration("20260829150747_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EcoPoints.Api.Domain.Canje", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<int>("PuntosGastados")
                        .HasColumnType("integer")
                        .HasColumnName("puntos_gastados");

                    b.Property<Guid>("RecompensaId")
                        .HasColumnType("uuid")
                        .HasColumnName("recompensa_id");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_canjes");

                    b.HasIndex("RecompensaId")
                        .HasDatabaseName("ix_canjes_recompensa_id");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_canjes_usuario_id");

                    b.ToTable("canjes", (string)null);
                });

            modelBuilder.Entity("EcoPoints.Api.Domain.CodigoValidacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("codigo");

                    b.Property<DateTime?>("ExpiraEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expira_en");

                    b.Property<Guid>("MisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("mision_id");

                    b.Property<DateTime?>("UsadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("usado_en");

                    b.Property<Guid?>("UsadoPor")
                        .HasColumnType("uuid")
                        .HasColumnName("usado_por");

                    b.HasKey("Id")
                        .HasName("pk_codigos_validacion");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_codigos_validacion_codigo");

                    b.HasIndex("MisionId")
                        .HasDatabaseName("ix_codigos_validacion_mision_id");

                    b.HasIndex("UsadoPor")
                        .HasDatabaseName("ix_codigos_validacion_usado_por");

                    b.ToTable("codigos_validacion", (string)null);
                });

            modelBuilder.Entity("EcoPoints.Api.Domain.Mision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean")
                        .HasColumnName("activa");

                    b.Property<DateTime>("CreadaEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creada_en");

                    b.Property<int?>("CupoMaximo")
                        .HasColumnType("integer")
                        .HasColumnName("cupo_maximo");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<int>("Puntos")
                        .HasColumnType("integer")
                        .HasColumnName("puntos");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("titulo");

                    b.Property<DateTime?>("VigenteDesde")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("vigente_desde");

                    b.Property<DateTime?>("VigenteHasta")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("vigente_hasta");

                    b.HasKey("Id")
                        .HasName("pk_misiones");

                    b.ToTable("misiones", null, t =>
                        {
                            t.HasCheckConstraint("ck_misiones_puntos", "puntos > 0");
                        });
                });

            modelBuilder.Entity("EcoPoints.Api.Domain.MovimientoPuntos", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid?>("CanjeId")
                        .HasColumnType("uuid")
                        .HasColumnName("canje_id");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<Guid?>("MisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("mision_id");

                    b.Property<int>("Puntos")
                        .HasColumnType("integer")
                        .HasColumnName("puntos");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_movimientos_puntos");

                    b.HasIndex("UsuarioId", "CreadoEn")
                        .HasDatabaseName("ix_movimientos_puntos_usuario_id_creado_en");

                    b.ToTable("movimientos_puntos", (string)null);
                });

            modelBuilder.Entity("EcoPoints.Api.Domain.Recompensa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean")
                        .HasColumnName("activa");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("ImagenUrl")
                        .HasColumnType("text")
                        .HasColumnName("imagen_url");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<int>("PuntosRequeridos")
                        .HasColumnType("integer")
                        .HasColumnName("puntos_requeridos");

                    b.Property<int>("Stock")
                        .HasColumnType("integer")
                        .HasColumnName("stock");

                    b.HasKey("Id")
                        .HasName("pk_recompensas");

                    b.ToTable("recompensas", null, t =>
                        {
                            t.HasCheckConstraint("ck_recompensas_puntos", "puntos_requeridos > 0");
                        });
                });

            modelBuilder.Entity("EcoPoints.Api.Domain.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("usuario")
                        .HasColumnName("rol");

                    b.HasKey("Id")
                        .HasName("pk_usuarios");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_usuarios_email");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("EcoPoints.Api.Domain.Canje", b =>
                {
                    b.HasOne("EcoPoints.Api.Domain.Recompensa", "Recompensa")
                        .WithMany()
                        .HasForeignKey("RecompensaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_canjes_recompensas_recompensa_id");

                    b.HasOne("EcoPoints.Api.Domain.Usuario", "Usuario")
                        .WithMany("Canjes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_canjes_usuarios_usuario_id");

                    b.Navigation("Recompensa");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("EcoPoints.Api.Domain.CodigoValidacion", b =>
                {
                    b.HasOne("EcoPoints.Api.Domain.Mision", "Mision")
                        .WithMany("Codigos")
                        .HasForeignKey("MisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_codigos_validacion_misiones_mision_id");

                    b.HasOne("EcoPoints.Api.Domain.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsadoPor")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_codigos_validacion_usuarios_usado_por");

                    b.Navigation("Mision");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("EcoPoints.Api.Domain.MovimientoPuntos", b =>
                {
                    b.HasOne("EcoPoints.Api.Domain.Usuario", "Usuario")
                        .WithMany("Movimientos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_movimientos_puntos_usuarios_usuario_id");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("EcoPoints.Api.Domain.Mision", b =>
                {
                    b.Navigation("Codigos");
                });

            modelBuilder.Entity("EcoPoints.Api.Domain.Usuario", b =>
                {
                    b.Navigation("Canjes");

                    b.Navigation("Movimientos");
                });
#pragma warning restore 612, 618
        }
    }
}
